### ISSUE TITLE
Height of sidebar is bigger than the height of the body

### ISSUE THREAD

**Issue by may42** [may42/may42.github.io#6]
В данный момент элементы sidebar и content имеют свойство float. Нужно заменить их отображение на какое-то другое, чтобы sidebar всегда отображался слева, был распахнут на всю высоту родителя, и чтобы content не съезжал вниз при узкой ширине экрана.

**Comment by may42** [comment]
Поломка страницы при малой ширине экрана исправлена следующим способом:

``` css
html, body, .content-container, .sidebar {
    height: 100%;
}
```

Но теперь полоса прокрутки показывается всё время, из-за того что высота html больше, чем высота видимой часть экрана. Как сделать её Равной высоте видимой части экрана?
